_reference_os: &reference_os # puntatore alla chiave
  linux # custom key

_reference_arch: &reference_arch
  amd64

_reference_jdk: &reference_jdk
  JDK="adopt@1.11"

language: minimal

git:
  depth: false
  autocrlf: input

os:
  - *reference_os
  - osx
  - windows

dist: focal

arch:
  - *reference_arch
  - arm64

env:
  global:
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
    - TERM="dumb"
  matrix:
    - *reference_jdk
    - JDK="adopt@1.8"
    - JDK="adopt@1.14"
    - JDK="adopt-openj9@1.11"
    - JDK="adopt-openj9@1.8"
    - JDK="adopt-openj9@1.14"

stages:
  - Compile
  - Kotlin Style Check
  - Complete Check
  - test

_reference_machine: &reference_machine
  arch: *reference_arch
  os: *reference_os
  env: *reference_jdk

_reference_workspace: &reference_workspace
  compiled_end

_import_workspace: &import_workspace
  workspaces:
    use: compiled_end

jobs:
  exclude:
    - arch: arm64
      env: JDK="adopt-openj9@1.8"
    - arch: arm64
      env: JDK="adopt-openj9@1.14"
    - <<: *reference_machine
      stage: test
  include:
    - <<: *reference_machine
      stage: Compile
      script: ./gradlew compileKotlin --parallel
      workspaces:
        create: *reference_workspace
        paths:
          - "$TRAVIS_BUILD_DIR"
          - "$HOME/.gradle"
    - <<: *reference_machine
      stage: Kotlin Style Check
      <<: *import_workspace
      script: ./gradlew detekt ktlintCheck --parallel
    - <<: *reference_machine
      stage: Complete Check
      <<: *import_workspace
      script:
        - travis_retry ./gradlew check

before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk

install:
  - "true"

script:
  - travis_retry ./gradlew test