if: repo != head_repo AND (tag IS blank OR tag =~ /\d+(\.\d+)*/)

_reference_os: &reference_os
                 linux
_reference_arch: &reference_arch
                   amd64
_reference_jdk: &reference_jdk
                  JDK="adopt@1.11"

language: minimal

git:
  depth: false
  autocrlf: input

os:
  - *reference_os
  - osx
  - windows

dist: focal

arch:
  - *reference_arch
  - arm64

env:
  global:
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
    - TERM="dumb"
  matrix:
    - *reference_jdk
    - JDK="adopt@1.8"
    - JDK="adopt@1.14"
    - JDK="adopt-openj9@1.11"
    - JDK="adopt-openj9@1.8"
    - JDK="adopt-openj9@1.14"

_repo_slug: &repo_slug
  NarcAle/LSS

stages:
  - Compile
  - Kotlin Style Check
  - Complete Check
  - name: test
    if: 'commit_message !~ /\[\s*skip(?: |-|\.)test\s*\].*/'
  - name: Delivery
    if: repo = NarcAle/LSS

_reference_machine: &reference_machine
  arch: *reference_arch
  os: *reference_os
  env: *reference_jdk

_workspace_name: &workspace_name
                   compiled_env

_import_workspace: &import_workspace
  workspaces:
    use: *workspace_name

jobs:
  exclude:
    - arch: arm64
      env: JDK="adopt-openj9@1.8"
    - arch: arm64
      env: JDK="adopt-openj9@1.14"
    - <<: *reference_machine
      stage: test
  include:
    - <<: *reference_machine
      stage: Compile
      script: travis_retry ./gradlew compileKotlin --parallel
      workspaces:
        create:
          name: *workspace_name
          paths:
            - "$TRAVIS_BUILD_DIR"
            - "$HOME/.gradle"
    - <<: *reference_machine
      stage: Kotlin Style Check
      <<: *import_workspace
      script: travis_retry ./gradlew detekt ktlintCheck --parallel
    - <<: *reference_machine
      stage: Complete Check
      <<: *import_workspace
      script:
        - travis_retry ./gradlew check
    - stage: Delivery
      before_script:
        - openssl aes-256-cbc -K $encrypted_f778b2e1574b_key -iv $encrypted_f778b2e1574b_iv -in secrets.asc.enc -out secrets.asc -d
        - export ORG_GRADLE_PROJECT_signingKey=$(cat secrets.asc)
        - rm secrets.asc
      script:
        - travis_retry ./gradlew publishMavenCentralPublicationToMavenRepository
      after_success:
        - ./gradlew publishPlugins -Pgradle.publish.key=$PLUGIN_PORTAL_KEY -Pgradle.publish.secret=$PLUGIN_PORTAL_SECRET
      before_deploy:
        - ./gradlew generateVersionFile
        - export VERSION = $(cat build/version)
        - git tag -a VERSION -m "Version $VERSION"
      deploy:
        - provider: releases
          file: "build/libs/*.jar" # Files to deploy
          edge: true # opt in to the new deploy API
          on: # filter
            all_branches: true


before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk

install:
  - "true"

script:
  - travis_retry ./gradlew test